// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tovvgyyvxnchlgzofocm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdnZneXl2eG5jaGxnem9mb2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzY3MTIsImV4cCI6MjA3MDE1MjcxMn0.Sdxzl3p6FGC9gserOSZkIJd9xwwupUpKya_Q7U9zVTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});